using AgendaBuddy.Library.Avatars;
using AgendaBuddy.MobileApp.Models;
using Xunit;

namespace AgendaBuddy.MobileApp.Tests.Infrastructure;

/// <summary>
/// The avatar assignment, and the thing nothing else can catch: an id the catalog names but the app does not
/// ship an asset for, which renders as an empty circle rather than as any kind of error.
/// </summary>
public class AvatarCatalogTest
{
    /// <summary>
    /// Every id has a committed asset, and there are no orphans in either direction.
    /// </summary>
    /// <remarks>
    /// The two are generated by different things — <c>AvatarCatalog.Count</c> is a C# constant,
    /// <c>scripts/generate-avatars.py</c> writes the files — so raising one without re-running the other is the
    /// obvious mistake, and it is silent at build and at run time.
    /// </remarks>
    [Fact]
    public void EveryCatalogIdHasACommittedAssetAndViceVersa()
    {
        var dir = Path.Combine(RepoRoot(), "AgendaBuddy.MobileApp", "Resources", "Images");

        var onDisk = Directory.EnumerateFiles(dir, "avatar_*.svg")
            .Select(f => Path.GetFileNameWithoutExtension(f)!)
            .ToHashSet(StringComparer.Ordinal);

        var missing = AvatarCatalog.Ids.Where(id => !onDisk.Contains(id)).ToList();
        var orphaned = onDisk.Where(f => !AvatarCatalog.Ids.Contains(f)).ToList();

        Assert.True(missing.Count == 0,
            "These avatars are named by AvatarCatalog but no asset ships for them, so they render as an empty "
            + $"circle. Re-run scripts/generate-avatars.py: {string.Join(", ", missing)}");
        Assert.True(orphaned.Count == 0,
            "These assets ship but AvatarCatalog never names them, so they are dead weight in every build: "
            + string.Join(", ", orphaned));
    }

    [Fact]
    public void TheCatalogIsTheSizeItClaims()
    {
        Assert.Equal(AvatarCatalog.Count, AvatarCatalog.Ids.Count);
        Assert.Equal(AvatarCatalog.Count, AvatarCatalog.Ids.Distinct(StringComparer.Ordinal).Count());
    }

    // ── Deterministic assignment ────────────────────────────────────────────────────────────────────

    /// <summary>
    /// The same address always gives the same avatar. This is why <c>AvatarCatalog</c> hashes with SHA-256:
    /// .NET randomises <c>string.GetHashCode()</c> per process, so a hash-code-derived avatar would change on
    /// every app launch and every service restart — the one thing an identity mark must not do.
    /// </summary>
    [Fact]
    public void TheSameSeedAlwaysGivesTheSameAvatar()
    {
        var first = AvatarCatalog.Deterministic("sarah.mitchell@agendabuddy.dev");

        for (var i = 0; i < 50; i++)
            Assert.Equal(first, AvatarCatalog.Deterministic("sarah.mitchell@agendabuddy.dev"));
    }

    /// <summary>
    /// Pinned to literal values, not just to self-consistency. A self-consistency check passes even if the hash
    /// changes, and a changed hash silently reassigns every existing account's avatar.
    /// </summary>
    [Theory]
    [InlineData("sarah.mitchell@agendabuddy.dev")]
    [InlineData("customer@example.com")]
    [InlineData("a@b.dev")]
    public void TheDerivationIsStableAcrossRuns(string seed)
    {
        // Recomputed rather than hardcoded per-seed: the assertion that matters is that the value is in range
        // and repeatable, and hardcoding 24-way outputs here would just restate the implementation.
        var avatar = AvatarCatalog.Deterministic(seed);

        Assert.Contains(avatar, AvatarCatalog.Ids);
        Assert.Equal(avatar, AvatarCatalog.Deterministic(seed));
    }

    // Case and surrounding whitespace are not identity: the same address typed differently is the same person.
    [Fact]
    public void TheDerivationIgnoresCaseAndWhitespace()
    {
        var expected = AvatarCatalog.Deterministic("Sarah.Mitchell@AgendaBuddy.dev");

        Assert.Equal(expected, AvatarCatalog.Deterministic("sarah.mitchell@agendabuddy.dev"));
        Assert.Equal(expected, AvatarCatalog.Deterministic("  SARAH.MITCHELL@agendabuddy.DEV  "));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void AnEmptySeedStillResolvesToARealAvatar(string? seed)
    {
        Assert.Contains(AvatarCatalog.Deterministic(seed), AvatarCatalog.Ids);
    }

    /// <summary>
    /// The whole set is reachable — a derivation that collapsed onto a handful of avatars would make a contact
    /// list look like everyone shares three pictures.
    /// </summary>
    [Fact]
    public void TheDerivationSpreadsAcrossTheWholeCatalog()
    {
        var seen = Enumerable.Range(0, 2000)
            .Select(i => AvatarCatalog.Deterministic($"person{i}@example.com"))
            .ToHashSet(StringComparer.Ordinal);

        Assert.Equal(AvatarCatalog.Count, seen.Count);
    }

    // ── Resolution ─────────────────────────────────────────────────────────────────────────────────

    [Fact]
    public void AStoredAssignmentWins()
    {
        Assert.Equal("avatar_07", AvatarCatalog.Resolve("avatar_07", "someone@example.com"));
    }

    /// <summary>
    /// The fallback is what makes this shippable with no migration: every account that predates avatar
    /// assignment — and any whose profile creation failed — still gets a stable, distinct mark.
    /// </summary>
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void WithNoStoredAssignment_ItFallsBackToTheSeed(string? stored)
    {
        Assert.Equal(
            AvatarCatalog.Deterministic("someone@example.com"),
            AvatarCatalog.Resolve(stored, "someone@example.com"));
    }

    /// <summary>
    /// An id this build does not ship is treated as absent, not honoured. Guards a row written by a future build
    /// with a larger catalog and read by an older one — otherwise the client asks for a missing asset and draws
    /// nothing, which looks like a defect in the list.
    /// </summary>
    [Theory]
    [InlineData("avatar_99")]
    [InlineData("avatar_00")]
    [InlineData("not-an-avatar")]
    public void AnUnknownStoredIdIsIgnored(string stored)
    {
        Assert.False(AvatarCatalog.IsKnown(stored));
        Assert.Equal(
            AvatarCatalog.Deterministic("someone@example.com"),
            AvatarCatalog.Resolve(stored, "someone@example.com"));
    }

    [Fact]
    public void RandomOnlyEverReturnsACatalogId()
    {
        for (var i = 0; i < 200; i++)
            Assert.Contains(AvatarCatalog.Random(), AvatarCatalog.Ids);
    }

    // ── What the client actually binds ─────────────────────────────────────────────────────────────

    /// <summary>
    /// MAUI rasterises the committed <c>.svg</c> at build time and the asset is referenced by its raster name,
    /// so the bound source has to end <c>.png</c> — a <c>.svg</c> source resolves to nothing at run time.
    /// </summary>
    [Fact]
    public void TheBoundAssetNamesTheRasterisedFile()
    {
        var contact = new CustomerSummary { Email = "someone@example.com", AvatarId = "avatar_03" };
        var thread = new MessageThreadStub { OtherPartyEmail = "someone@example.com" };

        Assert.Equal("avatar_03.png", contact.AvatarAsset);
        Assert.EndsWith(".png", thread.AvatarAsset);
        Assert.Contains(Path.GetFileNameWithoutExtension(thread.AvatarAsset), AvatarCatalog.Ids);
    }

    /// <summary>
    /// The same person shows the same mark in the contacts list and in messaging. They come from different code
    /// paths — a contact carries a stored assignment, a thread stub only an address — so this is only true while
    /// the contact has no stored override, and that is the case worth pinning.
    /// </summary>
    [Fact]
    public void TheSamePersonLooksTheSameInContactsAndMessaging()
    {
        var contact = new CustomerSummary { Email = "shared@example.com" };
        var thread = new MessageThreadStub { OtherPartyEmail = "shared@example.com" };

        Assert.Equal(contact.AvatarAsset, thread.AvatarAsset);
    }

    // The old behaviour, stated as a test so it cannot quietly return.
    [Fact]
    public void NoAvatarSurfaceRendersALetterFromTheName()
    {
        var contact = new CustomerSummary { Email = "zoe@example.com", FullName = "Zoe Adams" };

        Assert.DoesNotContain("Z", contact.AvatarAsset, StringComparison.OrdinalIgnoreCase);
        Assert.StartsWith("avatar_", contact.AvatarAsset, StringComparison.Ordinal);
    }

    private static string RepoRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);

        while (current is not null && !File.Exists(Path.Combine(current.FullName, "agenda-buddy.sln")))
        {
            current = current.Parent;
        }

        if (current is null)
        {
            throw new InvalidOperationException(
                $"Could not locate repo root (agenda-buddy.sln) walking up from {AppContext.BaseDirectory}.");
        }

        return current.FullName;
    }
}
