name: agenda-buddy-solution

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka0
      - schema-registry
      - broker
   
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
  
  broker:
    image: confluentinc/cp-server:7.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
  
  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      broker:
        condition: service_healthy
  
  kafka0:
    image: confluentinc/cp-kafka:7.2.1
    hostname: kafka0
    container_name: kafka0

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - kafka0
  
  provider:
    hostname: provider
    container_name: provider
    image: ${DOCKER_REGISTRY-}provider:latest
    build:
      context: .
      dockerfile: Provider/Dockerfile
  
  # services-api:
  #   hostname: services-api
  #   container_name: services-api
  #   image: ${DOCKER_REGISTRY-}services:latest
  #   build:
  #     context: .
  #     dockerfile: Services/Dockerfile

  events:
    hostname: events
    container_name: events
    image: ${DOCKER_REGISTRY-}eventandcommands:latest
    build:
      context: .
      dockerfile: EventAndCommands/Dockerfile
  
  kafka-library:
      image: ${DOCKER_REGISTRY-}kafka:latest
      build:
        context: .
        dockerfile: Kafka/Dockerfile

  common-library:
      image: ${DOCKER_REGISTRY-}library:latest
      build:
        context: .
        dockerfile: Library/Dockerfile
