variable "environment_name" {
  description = "azd/GitHub Environment name for this environment (e.g. staging, production). Drives resource names and the OIDC federated-credential subject, so it must exactly match the GitHub Environment name."
  type        = string
}

variable "location" {
  description = "Azure region for this environment's resource group."
  type        = string
}

variable "subscription_id" {
  description = "Azure subscription this environment deploys into."
  type        = string
}

variable "tenant_id" {
  description = "Entra tenant that owns the app registration and role assignments."
  type        = string
}

variable "github_repository" {
  description = "owner/repo the federated credential trusts (e.g. ogdevlabs/agenda-buddy)."
  type        = string
  default     = "ogdevlabs/agenda-buddy"
}

# Secret values below have no source to automate from — a fresh Atlas cluster or JWT keypair
# has to be generated by a human once per environment (see docs/deployment.md). What this
# config automates is *where they end up* (this environment's own Key Vault, RBAC-scoped to
# this environment's deploy identity only) rather than a human running `azd env set` by hand.

variable "agenda_buddy_connection_string" {
  description = "MongoDB Atlas connection string for the agenda_buddy database (6 domain services)."
  type        = string
  sensitive   = true
}

variable "identity_db_connection_string" {
  description = "MongoDB Atlas connection string for IdentityDb."
  type        = string
  sensitive   = true
}

variable "jwt_public_key" {
  description = "RSA public key (PEM) for JWT verification, generated fresh for this environment."
  type        = string
  sensitive   = true
}

variable "jwt_private_key" {
  description = "RSA private key (PEM) for JWT signing, generated fresh for this environment."
  type        = string
  sensitive   = true
}

variable "key_vault_purge_protection" {
  description = "Whether this environment's Key Vault blocks purging after deletion. Leave true for anything holding real data; set false for a throwaway environment, where an un-purgeable globally-unique name blocks destroy/re-apply for the whole retention window."
  type        = bool
  default     = true
}
