<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Profession-FB9A8FBA-510D-481A-BAD1-6E7C0DAC5E1C</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="12.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
      <PackageReference Include="MiniValidation" Version="0.9.1" />
      <PackageReference Include="MongoDB.Driver" Version="2.25.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventAndCommands\EventAndCommands.csproj" />
      <ProjectReference Include="..\Library\Library.csproj" />
      <ProjectReference Include="..\Library.ServerAuth\Library.ServerAuth.csproj" />
    </ItemGroup>
</Project>
