// Global using directives

global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Text.Json;
global using Confluent.Kafka;
global using Customer.Configurations;
global using Customer.Events;
global using Customer.Extensions;
global using Customer.Requests;
global using EventAndCommands.Commands.Customer;
global using EventAndCommands.Commands.Kafka;
global using EventAndCommands.Events.Kafka;
global using EventAndCommands.Messages;
global using EventAndCommands.Queries.Customers;
global using Kafka;
global using Kafka.Producer;
global using Kafka.Support;
global using KafkaFlow;
global using KafkaFlow.Configuration;
global using KafkaFlow.Producers;
global using KafkaFlow.Serializer;
global using Library.Entities;
global using Library.Events;
global using Library.Repositories;
global using Library.Services;
global using Library.Tools;
global using MediatR;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.WebUtilities;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Net.Http.Headers;
global using MiniValidation;
global using MongoDB.Bson;
global using MongoDB.Driver;
global using Acks = KafkaFlow.Acks;