<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <Authors>Oscar Garcia</Authors>
        <Copyright>OGDevLabs</Copyright>
        <Company>OGDevLabs</Company>
        <NeutralLanguage>en</NeutralLanguage>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="KafkaFlow" Version="3.0.7"/>
        <PackageReference Include="KafkaFlow.LogHandler.Console" Version="3.0.7"/>
        <PackageReference Include="KafkaFlow.Microsoft.DependencyInjection" Version="3.0.7"/>
        <PackageReference Include="KafkaFlow.Serializer.JsonCore" Version="3.0.7"/>
        <PackageReference Include="MediatR" Version="12.2.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Library\Library.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Consumer\" />
      <Folder Include="Extensions\" />
    </ItemGroup>

</Project>
