namespace AgendaBuddy.MobileApp.Resources.Strings;

public static class ProfessionDisplayNames
{
    internal static IReadOnlyDictionary<string, string> ResourceKeys { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Accounting"] = "Profession_001",
            ["Addiction"] = "Profession_002",
            ["Artificial Intelligence"] = "Profession_003",
            ["Pet Training"] = "Profession_004",
            ["Anti-Aging"] = "Profession_005",
            ["Aquaculture Technology"] = "Profession_006",
            ["Architecture"] = "Profession_007",
            ["Art"] = "Profession_008",
            ["Assisted Living"] = "Profession_009",
            ["Attendee Experience"] = "Profession_010",
            ["Automation"] = "Profession_011",
            ["Automotive"] = "Profession_012",
            ["Beauty"] = "Profession_013",
            ["Bitcoin"] = "Profession_014",
            ["Bodybuilding"] = "Profession_015",
            ["Boxing"] = "Profession_016",
            ["Business"] = "Profession_017",
            ["Cannabis"] = "Profession_018",
            ["Career Planning"] = "Profession_019",
            ["Change Management"] = "Profession_020",
            ["Charity & Non-Profits"] = "Profession_021",
            ["Chiropractic"] = "Profession_022",
            ["Coaching"] = "Profession_023",
            ["Comedy"] = "Profession_024",
            ["Communication"] = "Profession_025",
            ["Construction"] = "Profession_026",
            ["Content Creation"] = "Profession_027",
            ["Counseling"] = "Profession_028",
            ["Crypto"] = "Profession_029",
            ["Culture"] = "Profession_030",
            ["Cybersecurity"] = "Profession_031",
            ["Dance"] = "Profession_032",
            ["Data"] = "Profession_033",
            ["DEI"] = "Profession_034",
            ["Dropshipping"] = "Profession_035",
            ["E-commerce"] = "Profession_036",
            ["Economics"] = "Profession_037",
            ["Education"] = "Profession_038",
            ["Electrical"] = "Profession_039",
            ["Energy"] = "Profession_040",
            ["Enterpise Asset Management"] = "Profession_041",
            ["Entertainment"] = "Profession_042",
            ["Entrepreneurship"] = "Profession_043",
            ["Environment"] = "Profession_044",
            ["Events"] = "Profession_045",
            ["Faith and Spirituality"] = "Profession_046",
            ["Family"] = "Profession_047",
            ["Fashion"] = "Profession_048",
            ["Fashion Modeling"] = "Profession_049",
            ["Film and TV"] = "Profession_050",
            ["Finance"] = "Profession_051",
            ["Firearms"] = "Profession_052",
            ["Food and Beverage"] = "Profession_053",
            ["Foreign Languages"] = "Profession_054",
            ["Franchises"] = "Profession_055",
            ["Gaming"] = "Profession_056",
            ["Gardening"] = "Profession_057",
            ["Government"] = "Profession_058",
            ["Graphing Design"] = "Profession_059",
            ["Health"] = "Profession_060",
            ["Health and Wellness"] = "Profession_061",
            ["Healthcare"] = "Profession_062",
            ["Health Tech"] = "Profession_063",
            ["Higher Education"] = "Profession_064",
            ["Hospitality"] = "Profession_065",
            ["Human Resources"] = "Profession_066",
            ["Insurance"] = "Profession_067",
            ["Intellectual Property (IP)"] = "Profession_068",
            ["Job Interviews"] = "Profession_069",
            ["Land Management"] = "Profession_070",
            ["Legal"] = "Profession_071",
            ["LGBTQ+"] = "Profession_072",
            ["Machine Learning"] = "Profession_073",
            ["Marketing"] = "Profession_074",
            ["Mechanic"] = "Profession_075",
            ["Mechanic Engineering"] = "Profession_076",
            ["Media"] = "Profession_077",
            ["Meditation"] = "Profession_078",
            ["Mental Health"] = "Profession_079",
            ["Military"] = "Profession_080",
            ["Mindfulness"] = "Profession_081",
            ["Mixed Martial Arts"] = "Profession_082",
            ["Music"] = "Profession_083",
            ["Networking"] = "Profession_084",
            ["Parenting"] = "Profession_085",
            ["Performing Arts"] = "Profession_086",
            ["Pharmacy"] = "Profession_087",
            ["Philosophy"] = "Profession_088",
            ["Podcasting"] = "Profession_089",
            ["Product Development"] = "Profession_090",
            ["Product Management"] = "Profession_091",
            ["Property Management"] = "Profession_092",
            ["Psychic"] = "Profession_093",
            ["Psychology"] = "Profession_094",
            ["Public Speaking"] = "Profession_095",
            ["Real State"] = "Profession_096",
            ["Relationships"] = "Profession_097",
            ["Retail"] = "Profession_098",
            ["Sales"] = "Profession_099",
            ["Self-Improvement"] = "Profession_100",
            ["Sexual Health"] = "Profession_101",
            ["Social Media"] = "Profession_102",
            ["Software Engineering"] = "Profession_103",
            ["Spirituality"] = "Profession_104",
            ["Sports"] = "Profession_105",
            ["Startups"] = "Profession_106",
            ["Supply Chain"] = "Profession_107",
            ["Systems Engineering"] = "Profession_108",
            ["Talent Acquisition"] = "Profession_109",
            ["Tarot"] = "Profession_110",
            ["Technology"] = "Profession_111",
            ["Trading"] = "Profession_112",
            ["Travel"] = "Profession_113",
            ["Video Creator"] = "Profession_114",
            ["Writing"] = "Profession_115"
        };

    public static string Get(string canonicalName)
    {
        if (!ResourceKeys.TryGetValue(canonicalName, out var resourceKey)
            || AppResources.CurrentCulture.TwoLetterISOLanguageName == "en")
        {
            return canonicalName;
        }

        return AppResources.GetString(resourceKey);
    }
}